"""Adding main module

Revision ID: 4db97518eddf
Revises: 92b5b5e67fb2
Create Date: 2024-01-25 15:17:36.382679

"""
from alembic import op
import sqlalchemy as sa

from server import utils

# revision identifiers, used by Alembic.
revision = '4db97518eddf'
down_revision = '92b5b5e67fb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    category_table = op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=68), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    patient_table = op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=68), nullable=True),
    sa.Column('surname', sa.String(length=68), nullable=True),
    sa.Column('_birthday', sa.Date(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    appointment_table = op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    measure_table = op.create_table('measure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marker', sa.String(length=68), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('_timestamp', sa.DateTime(), nullable=True),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # #### Main
    bulk_categories = [{"id": 1, "name": "HR"}, {"id": 2, "name": "Boold Pressure"}]
    op.bulk_insert(category_table, bulk_categories)

    bulk_patient = [{"id": 1, "name": "Luca", "surname": "Nastasi", "birthday": utils.parse_date("28.07.1997")}]
    op.bulk_insert(patient_table, bulk_patient)

    bulk_appointment = [{"id": 1, "date": utils.parse_date("1.1.2024"), "patient_id": 1}]
    op.bulk_insert(appointment_table, bulk_appointment)

    bulk_measure = [{"id": 1, "timestamp": utils.parse_timestamp("1.1.2024 11:00:00.112"),
                     "category_id": 1, "appointment_id": 1},
                    {"id": 2, "timestamp": utils.parse_timestamp("1.1.2024 11:00:01.112"),
                     "category_id": 1, "appointment_id": 1}
                    ]
    op.bulk_insert(measure_table, bulk_measure)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measure')
    op.drop_table('appointment')
    op.drop_table('patient')
    op.drop_table('category')
    # ### end Alembic commands ###
